imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/packages.yml?raw=true

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010

#Dv2 and Dv3 VMs
  d2v2:
    variables:
      serverPort: 5000
      serverAddress: 172.27.1.5
      cores: 2
    jobs:
      db:
        endpoints:
          - http://172.27.1.11:5010
      application:
        endpoints:
          - http://172.27.1.5:5010
        variables:
          databaseServer: 172.27.1.11
      load:
        endpoints:
          - http://172.27.1.9:5010
          
  d2v3:
    variables:
      serverPort: 5000
      serverAddress: 172.27.1.6
      cores: 2
    jobs:
      db:
        endpoints:
          - http://172.27.1.11:5010
      application:
        endpoints:
          - http://172.27.1.6:5010
        variables:
          databaseServer: 172.27.1.11
      load:
        endpoints:
          - http://172.27.1.9:5010
  d3v2:
    variables:
      serverPort: 5000
      serverAddress: 172.27.1.4
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.27.1.11:5010
      application:
        endpoints:
          - http://172.27.1.4:5010
        variables:
          databaseServer: 172.27.1.11
      load:
        endpoints:
          - http://172.27.1.9:5010
  d4v3:
    variables:
      serverPort: 5000
      serverAddress: 172.27.1.7
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.27.1.11:5010
      application:
        endpoints:
          - http://172.27.1.7:5010
        variables:
          databaseServer: 172.27.1.11
      load:
        endpoints:
          - http://172.27.1.9:5010
  d8v3:
    variables:
      serverPort: 5000
      serverAddress: 172.27.1.8
      cores: 8
    jobs:
      db:
        endpoints:
          - http://172.27.1.11:5010
      application:
        endpoints:
          - http://172.27.1.8:5010
        variables:
          databaseServer: 172.27.1.11
      load:
        endpoints:
          - http://172.27.1.9:5010

#Ds_v4 & Ds_v5 VMs
  d4sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.8
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.8:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d4sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.9
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.9:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d8sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.10
      cores: 8
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.10:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d8sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.11
      cores: 8
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.11:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d16sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.12
      cores: 16
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.12:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d16sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.14
      cores: 16
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.14:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d32sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.13
      cores: 32
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.13:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d32sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.15
      cores: 32
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.15:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d48sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.16
      cores: 48
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.16:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d48sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.17
      cores: 48
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.17:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d64sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.18
      cores: 64
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.18:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010

  d64sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.19
      cores: 64
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.19:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010          

  e4sv3:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.22
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.22:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010         

  e4sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.21
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.21:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e4sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.23
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.23:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e8sv3:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.24
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.24:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e8sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.25
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.25:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e8sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.26
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.26:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e16sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.27
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.27:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e16sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.28
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.28:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e32sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.29
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.29:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010        

  e32sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.30
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.30:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010       

  e48sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.31
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.31:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010       

  e48sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.32
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.32:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010       

  e48sv4:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.33
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.33:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010       

  e64sv5:
    variables:
      serverPort: 5000
      serverAddress: 172.16.1.34
      cores: 4
    jobs:
      db:
        endpoints:
          - http://172.16.1.7:5010
      application:
        endpoints:
          - http://172.16.1.34:5010
        variables:
          databaseServer: 172.16.1.7
      load:
        endpoints:
          - http://172.16.1.6:5010
